services:
  web:
    environment:
      FLOWMIND_CONTROL_CONFIG: /app/results/control/selected_control.json
    networks:
      - default
      - myhaven_proxy

networks:
  myhaven_proxy:
    external: true
    name: myhaven_default
